### PR TITLE
Enable support for SonarQube 6.5

### PR DESCRIPTION
**Pull request by bradflood**

### CODE REVIEW

**Comment by bradflood** [comment]
Hi Alexandre - I would appreciate some feedback on this PR when you get a minute.

**Comment by VinodAnandan** [comment]
@alexvictoor

**Comment by VinodAnandan** [comment]
@bradflood  Thank you very much for your valuable contribution to sonar-pitest plugin.

**Comment by VinodAnandan** [comment]
#12 #13

**Pull request merged**
